blog/site-to-site-wireguard-part-1-2019-04-02.markdown, blog/site-to-site-wireguard-part-2-2019-04-07.markdown, blog/site-to-site-wireguard-part-3-2019-04-11.markdown
=> blog: WireGuard Site to Site VPN Part 3 - Custom TLS Certificate Authority

cmd/site/html.go
Puts them in [/metrics](https://christine.website/metrics)
=> cmd/site: show talk viewcounts broken down with blogposts

blog/olin-1-why-09-1-2018.markdown
Fix some minor spelling mistakes in `olin-1-why-09-1-2018.markdown` that I happen to come across.
=> Fix spelling in blog post "Olin: 1: Why"

signalboost.dhall
Thanks for doing this, Xe. I know it's not much, but it means a lot to me.
=> Update signalboost.dhall, adding DDR as a job-seeker.

blog/ios-development-pro-tip-for-private-ca-2019-03-22.markdown, blog/templeos-1-installation-and-basic-use-2019-05-20.markdown, blog/wasmcloud-progress-2019-12-08.markdown
I found more broken images on the following pages:
- https://christine.website/blog/ios-development-pro-tip-for-private-ca-2019-03-22
- https://christine.website/blog/templeos-1-installation-and-basic-use-2019-05-20
- https://christine.website/blog/wasmcloud-progress-2019-12-08
Implemented a fix in the same way as #224
=> delete <center> tags on images

blog/nixos-desktop-flow-2020-04-25.markdown
Hi Xe,
this post gave me a lot and I want to give you something back by fixing some broken links to your GitHub files.
I chose to pin them to commits that were the latest right before you first published this post, so they are consistent with the snippets inside the post. I also pinned the gruvbox-css `default.nix` even though the link is working because this not only makes sure the contents behind the link will stay persistent with the post in case you choose to change something in there, but also because this enables others to clone the repo, check out the exact commit and try it out on their own.
I intentionally left some links (like those to your fish / spacemacs / etc. configs) unchanged so that they will always point to the latest files because they are just further examples of what …
=> Fix broken file links

static/js/hnwarn.js
As mentioned in IRC.
reddit supports any two-letter code in its subdomain, and has a few special subdomains (`np` for No Participation, `new` for new reddit, `old` for old reddit, and `www`, to name a few). I expect the latter to be more often used, but it's worth throwing a blanket case over every reddit subdomain.
I structured my patch with the expectation that you don't want some sort of other behavior for certain referrers, although it's not too hard to add differing behavior for different categories of sites should you choose.
=> Improve domain matching for nag warning, add more reddit domains

blog/nix-flakes-1-2022-02-21.markdown
Sadly using ssh+git does not work. I tested this locally.
See also: https://discourse.nixos.org/t/url-format-for-flake-over-git-ssh/7538/2
EDIT: I really enjoyed that post, keep up the great work!
=> fix small content error: nix flakes can access private repos with git+ssh

blog/nix-flakes-1-2022-02-21.markdown
Nix 2.7 renamed a bunch of the default flake attributes: https://nixos.org/manual/nix/stable/release-notes/rl-2.7.html
In Nix 2.8, nix run fails if `defaultApps` is used with an error like this: `error: attribute 'defaultApp.aarch64-linux' should have type 'derivation'`
This uses the new default syntax, which fixes that. Not sure if this should now call out that it requires Nix 2.7 or later. The `pkgs.nixFlakes` package in the installation section gets 2.8 for me, so people might already be getting it.
=> Fix examples to work with Nix >= 2.7

blog/nix-flakes-1-2022-02-21.markdown
Good old Nix changing things. I've also noted the branch format, since they hard-coded it to master by default.
=> Fix the flake URL format

blog/my-career-in-dates-titles-salaries-2019-03-14.markdown, blog/site-update-salary-transparency.markdown, config.dhall, default.nix, dhall/authors.dhall, dhall/jobHistory.dhall, dhall/signalboost.dhall, dhall/types/Author.dhall, dhall/types/Job.dhall, dhall/types/Person.dhall, dhall/types/Salary.dhall, src/app/markdown.rs, src/app/mod.rs, src/handlers/mod.rs, src/main.rs, src/post/mod.rs, src/signalboost.rs, src/tmpl/mod.rs, templates/footer.rs.html, templates/header.rs.html, templates/salary_transparency.rs.html, templates/signalboost.rs.html
* Move dhall data and types into `/dhall` folder
* Reformat salary transparency data into Dhall
* Wire up the old salary transparency page with a custom element
* Wire up a new salary transparency page
* Expose raw data as JSON
* Make dhall types more portable
* Remove gallery from the navbar
* Make signal boost page point to the new data location
* Add salary transparency page to the footer of the site
* Add site update post for this
Signed-off-by: Xe <me@xeiaso.net>
=> Add salary transparency page

blog/site-update-salary-transparency.markdown, templates/salary_transparency.rs.html
`s/hirt/hurt/`, as discussed on IRC.
=> Typo fixes on the salary transparency pages

blog/nix-flakes-1-2022-02-21.markdown
Hi,
As per updated in https://github.com/NixOS/nix/pull/6089, `devShell` has been renamed to `devShells`.
https://github.com/NixOS/nix/blob/4248174e7165f48f92416d13b862e3ef8192a34b/src/nix/flake.cc#L516
=> blog: update devShell to devShells for compatibility with recent spec

blog/fun-with-redirection-2021-09-22.markdown, blog/rust-crates-go-stdlib-2020-09-27.markdown
In your stream reviewing #518, you mentioned that your website is cloned locally to the `code/christine.website` folder. You reverted a few changes to this folder name. This PR reverts the rest of the changes to `code/christine.website`.
=> Domain move 2: code/christine.website

blog/how-i-start-rust-2020-03-15.markdown
This PR fixes a missing link in the blog post [How I Start: Rust](https://xeiaso.net/blog/how-i-start-rust-2020-03-15).
=> Fix missing Docker link in "How I Start: Rust"

blog/how-i-start-nix-2020-03-08.markdown
Was reading your article (great btw) and saw that the lorri tool moved to new repo so here's a small PR with updated URL to lorri
=> Update lorri repo link in how-i-start-nix-2020-03-08.markdown

dhall/signalboost.dhall, dhall/types/Person.dhall, src/signalboost.rs, templates/signalboost.rs.html
Also in this commit:
* Add linkedin and cover_letter (per https://github.com/Xe/site/pull/550#discussion_r1019824691) anmong other things,
including adding fediverse and website fields
* Update the signalboost.rs HTML template to reflect
these changes to Person.dhall types
=> signalboost: add entry for ~ajhalili2006

static/css/hack.css
In some situations, mobile devices (in this case, Safari on iOS when in landscape orientation) applies a text inflation algorithm to the page's content. This is to ensure readability of text, in cases where the device has resorted to rendering the desktop layout, shrunk it down, and now needs to blow up the text to compensate. 
The heuristics it uses to determine this are... weird, and can make for some strange jumps in text size, even between elements that are otherwise styled the same. 
(This also affects various other elements around the site, and as the text inflation heuristics are applied on a page-by-page basis, this sometimes means parts of the header and footer can sometimes be different sizes on different pages. Wild.) 
Given the site has a whole "one size fits all" approach to …
=> Fix text size inflation in some mobile contexts

blog/waifud-progress-2022-02-06.markdown
Currently, the `waifud` series only covers the introductory plans post, as well as the second progress report.
This PR adds the first progress report to that series as well. I'm not sure if this is the only place to update this tag though
=> Add missing `waifud` article to the `waifud` series

dhall/signalboost.dhall
In a nutshell:
* nuked Twitter link but adds GitLab + sourcehut + Substack profile links
* point website to `andreijiroh.eu.org` instead of my buffer start.page
* add [#ActuallyAutistic](https://anagora.org/actuallyautistic) tag (this may affect chances of getting employed, but it'll potentially help with discovery for other ND people)
=> Update signalboost entry for ~ajhalili2006

lume/src/_includes/blog.njk
> Uncaught TypeError: navigator.canShare is not a function
`navigator.canShare` is under a [settings flag](https://caniuse.com/mdn-api_navigator_canshare) in firefox, and also completely missing from some other browsers/versions, so we need to check general availability first
this fix will fallback to copying url into clipboard
same should be done for `vod.njk` and `talk.njk`, but maybe you'd want to separate this into its own script-file, so i changed it just in `blog.njk`
=> fix blogpost sharing button from non-chromium browsers

internal/lume/lume.go, lume/_config.ts, lume/src/_includes/blog.njk, lume/src/blog.jsx, lume/src/index.njk, lume/src/talks.jsx, lume/src/vods.jsx
adds [`<time>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/time) tag to dates.
1. [improves accessibility for date](https://shkspr.mobi/blog/2020/12/making-time-more-accessible/).
2. simplify code more by utilizing lume's [date plugin](https://lume.land/plugins/date/) more and replace [toLocaleDateString](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleDateString)
3. ~~make my force iso8601 date userscript work~~
```js
Array.from(document.querySelectorAll("time"))
.filter((node) => !node.children.length)
.forEach((node) => (node.innerText = node.getAttribute("datetime")))
```
=> feat: use time tag for date

lume/src/notes/2024/xz-vuln.mdx
Fedora 40 beta release is not affected, but update-testing repository is. In my experience is common for beta users to have that repo enabled. I think it's by default but can't confirm.
=> Fedora 40 beta is also affected

lume/src/notes/2024/xz-vuln.mdx
Currently Fedora 41 _is_ rawhide. Fedora 40 is the affected branch.
=> Reference correct Fedora version

lume/src/resume.njk
Corrected a minor spelling error in the job title, probably just a one-off typo.
This ensures the correct French term `fiabilité` (reliability) is used instead of the incorrect `fiabileté`. 
_It ain't much, but it's honest work._
=> fix: correct spelling in resume
