blog/coding-on-an-ipad-2018-04-14-2018.markdown
Mostly stream of consciousness first draft material. Please rip this to
shreds.
=> blog: add first draft of coding on an iPad

blog/when-then-zen-2019-01-20.md
Sorry about the end of file line, think GitHub's web editor tossed that in.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/xe/site/16)
=> Update Gherkin link

blog/practical-kasmakfa-2019-04-21.markdown
=> blog: practical kasmakfa

blog/ipad-smart-keyboard-accents-2019-05-10.markdown
This is so hard to google for. I'm making it easier.
=> blog: explain how to type french accents on iOS with an iPad Smart Keyboard

static/resume/resume.md
add ordination as well as update some things
=> static/resume: update

talks/webassembly-on-the-server-system-calls-2019-05-31.markdown
=> talks: add WebAssembly on the Server talk

blog/mr-beast-postmodern-gold-2019-06-05.markdown, templates/contact.html
=> MrBeast Post

css/hack.css
Look at all that shit.
Prettier.js got trigger happy, all you really want is this:
Here's what it should look like. If you want to override the link styles or headers just add extra tag overrides `a::selection {background: #color}` or whatever
=> AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

blog/h-language-2019-06-30.markdown
=> blog: add h langauge post

static/resume/resume.md
Was linked from r/programming and saw this small typo.
Enjoyed the article on h!
=> Fix currently spelling

blog/h-language-2019-06-30.markdown
I was reading this again and noticed this typo.
Amazing work!
=> fix grammar on h post - "is ran" => "is run"

blog/howto-usermode-linux-2019-07-07.markdown
=> blog: user mode linux post

blog/the-cheese-dream-2019-10-01.markdown
My dreams are a ride.
Based on this twitter thread: https://twitter.com/theprincessxena/status/1178996989385740288?s=21
=> blog: add the cheese dream

blog/get-going-hello-world-2019-10-28.markdown
This is a draft of the first chapter of Get Going, my book on how to program in the [Go](https://golang.org). I'm intending to post this to my blog so that I can get feedback on what is and is not being done correctly.
Thanks @faithanalog for feedback on this draft.
=> blog/get-going-hello-world: second draft

blog/gears-and-gods-2019-11-14.markdown
Based on this twitter rant: https://twitter.com/theprincessxena/status/1195092328337354766
=> blog: The Gears and The Gods

blog/toast-sandwich-recipe-2019-12-02.markdown
I swear this is every cooking blog ever.
=> blog: post on toast sandwiches

blog/irc-chghost-2013-10-04.markdown
This is from 2013. It is quite possibly one of my oldest writings on the internet.
=> blog: add IRC CHGHOST capability spec

blog/why-rust-2020-02-15.markdown
Done on stream!
Closes #13 I guess
=> blog: Why Rust, A Tale of Satori

blog/how-i-start-nix-2020-03-08.markdown
There was more that I wanted to change, but these are the only things that _needed_ to be changed.
=> Light proof reading.

blog/how-i-start-rust-2020-03-15.markdown
For submission to [howistart](https://howistart.org).
=> blog: add How I Start: Rust

signalboost.dhall
In response to - https://christine.website/blog/signalboost-page-2020-03-20
=> signalboost: add Prajjwal

blog/reconlangmo-2-phonology-writing-2020-05-08.markdown
https://www.reddit.com/r/conlangs/comments/gfp3hw/reconlangmo_2_phonology_writing/
=> blog: reconlangmo 2 - phonology and writing

blog/reconlangmo-2-phonology-writing-2020-05-08.markdown, blog/reconlangmo-5-sentence-structure-2020-05-18.markdown
https://www.reddit.com/r/conlangs/comments/gmbwb5/reconlangmo_5_sentence_structure/
=> reconlangmo 5: Sentence Structure

static/resume/resume.md, templates/index.html
=> Just call yourself a full stack engineer

blog/reconlangmo-7-discourse-2020-05-25.markdown
Also include the beginning of the treatise against binary gender in language
=> reconlangmo 7: discourse

nix/sources.json, shell.nix, site.nix
=> Nixpkgs unstable

css/hack.css, templates/signalboost.html
=> tweak css for signalboost

css/hack.css
=> fixed columns on signalboost

signalboost.dhall
=> fix(signalboost): add twitter details to dude

blog/drone-kubernetes-cd-2020-07-10.markdown
Also details the printer facts API.
=> Continuous Deployment to Kubernetes with Gitea and Drone

signalboost.dhall
Hi Christine, thanks for the great blog and idea of signalboost. Hoping that it makes a difference to all the people who has put their names up there. 
I'm proud that my first advertisement for job is in here:-)
As part of building my profile, I have started a [blog](https://jeffin.jusfocus.com/). I am just prematurely pushing a post on wireguard so that you could check it out. Find out your blog by searching for wireguard. 
Thanks once again
=> signalboost - jeffin added

blog/how-mara-works-2020-09-30.markdown
Explain how the shörk works and get into the `<picture>` element.
=> How mara works

signalboost.dhall
I think Jamie GitHub handle is @AstraLuma
=> fix Jamie's GitHub link

css/hack.css
fixes https://github.com/Xe/site/issues/238
Disclaimer: I only tested this with the browser developer tools. I did not rebuild the site or try this CSS change on multiple pages.
=> Fix CSS bug where code blocks ended with blank lines in Firefox

signalboost.dhall
=> Added Joseph Crawley into signalboost.dhall

signalboost.dhall
=> signalboost: Add nicoo

blog/TLDR-rust-2020-09-19.markdown, blog/minicompiler-lexing-2020-10-29.markdown, blog/rust-crates-go-stdlib-2020-09-27.markdown
=> minicompiler: lexing

blog/scavenger-hunt-solution-2020-11-25.markdown
=> add blogpost explaining the scavenger hunt

Cargo.lock, blog/nixos-discord-webhook-11-30-2020.markdown, blog/nixos-discord-webhook-2020-11-30.markdown, nix/sources.json
Also do some much needed updates.
=> add nixos/discord webhook post

Cargo.lock, Cargo.toml, blog/webmention-support-2020-12-02.markdown, config.dhall, lib/mi/Cargo.toml, lib/mi/src/lib.rs, nix/rust.nix, nix/sources.json, shell.nix, site.dhall, src/app/mod.rs, src/post/mod.rs, templates/blogpost.rs.html
=> add webmention support

signalboost.dhall
Addition of Nasir Hussain in Signalboost.
=> add: nasirhm in signalboost

templates/blogpost.rs.html, templates/gallerypost.rs.html, templates/series_posts.rs.html, templates/talkpost.rs.html
Remove time/tz info which isn't provided by blog posts anyway.
Finally fixed it for ya'. :)
=> Fix Twitter/JSON-LD timestamps

signalboost.dhall
=> Add self to signalboost

signalboost.dhall
=> chore(signalboost): Add linuxgemini

Cargo.lock, Cargo.toml, lib/cfcache/Cargo.toml, lib/go_vanity/Cargo.toml, lib/mi/Cargo.toml, lib/patreon/Cargo.toml, src/app/poke.rs, src/handlers/mod.rs, templates/blog_atom.rs.xml, templates/footer.rs.html
Closes #302 
Closes #301
Closes #297
Closes #290
Closes #288
Closes #273 
Closes #305
=> Use Tokio 1

blog/identity-model-software-2021-01-31.markdown
Upside, inside out, living la vida loca!
=> blog: a model for identity in software

blog/my-wireguard-setup-2021-02-06.markdown
=> blog: detail my next-generation wireguard setup

blog/how-to-handle-pedophiles-in-communities-2021-03-07.markdown
=> first draft

css/gruvbox-dark.css, src/handlers/blog.rs, src/handlers/feeds.rs, src/handlers/gallery.rs, src/handlers/mod.rs, src/handlers/talks.rs
Closes https://github.com/Xe/site/issues/329
=> css/gruvbox-dark: enable light mode if the os tells me to

signalboost.dhall
Got a job on my own!
Thank you for offering this space to advertise!
=> signalboost: Remove ansimita

blog/furnal-equinox-2021-03-22.markdown
=> blog: Furnal Equinox post

blog/dev-printerfact-2021-04-17.markdown, src/app/mod.rs
=> /dev/printerfact post

signalboost.dhall
=> Remove linuxgemini

blog/morph-setup-2021-04-25.markdown, src/app/markdown.rs, templates/mara.rs.html
=> blog: add morph tutorial

signalboost.dhall
=> signalboost: add syntaqx

talks/systemd-the-good-parts-2021-05-16.markdown
Do not merge and deploy until tomorrow at 11 am.
=> talks: add systemd: the good parts

signalboost.dhall
Reverts Xe/site#364 - Gots a jerb. Thank you for da boost 🚀
=> Revert "signalboost: add syntaqx"

blog/android-thoughts-2021-07-04.markdown
=> Thoughts on Android

blog/emoji-not-language-2021-07-14.markdown
=> emoji is not a language

Cargo.lock, Cargo.toml, css/gruvbox-dark.css, css/hack.css, css/shim.css, src/app/markdown.rs, templates/blogpost.rs.html, templates/header.rs.html
Still WIP: the theme is not right, the margins/padding are off, etc.  But it works!
=> markdown: use comrak syntect

blog/fun-with-redirection-2021-09-22.markdown
=> clarify some language; insert spaces in args to confuse beginners less

blog/theres-a-node-2021-10-02.markdown
=> there's a node in the cluster in the cloud

blog/vtubing-setup-2022-01-13.markdown
Signed-off-by: Xe Iaso <me@christine.website>
=> How I VTuber

blog/nix-flakes-1-2022-02-21.markdown, blog/nix-flakes-4-wsl-2022-04-23.markdown, blog/nix-flakes-4-wsl-2022-05-01.markdown
=> Nix flakes 4 wsl

signalboost.dhall
Hi great idea :) Add me to the single boost.
=> Signal Booster

static/resume/resume.md
Solves #482 without touching anything else in the résumé :)
=> Switch to xeiaso.net links in resume.md

signalboost.dhall
I love the blog and am actively looking for another opportunity.
=> Signal Boost

blog/stanley-parable.markdown
Signed-off-by: Xe <me@christine.website>
=> The Stanley Parable

css/hack.css
=> Add a bit of vertical margin to .container

blog/cinemaquestria-orchestration-2015-03-13.markdown, blog/coding-on-an-ipad-2018-04-14-2018.markdown, blog/drone-kubernetes-cd-2020-07-10.markdown, blog/gitea-release-tool-2020-05-31.markdown, blog/how-i-start-rust-2020-03-15.markdown, blog/howto-usermode-linux-2019-07-07.markdown, blog/land-1-syscalls-file-io-2018-06-18.markdown, blog/nix-flakes-4-wsl-2022-05-01.markdown, blog/pursuit-of-dsl-2014-08-16.markdown, blog/reconlangmo-6-lexicon-2020-05-22.markdown, blog/site-to-site-wireguard-part-4-2019-04-16.markdown, blog/social-media-psychic-cancer-2021-07-29.markdown, blog/the-origin-of-h-2015-12-14.markdown, blog/the-universal-design-2015-10-17.markdown, blog/twitter-2022-04-25.markdown, blog/when-then-zen-anapana-2018-08-15.markdown, dhall/signalboost.dhall, static/resume/resume.md, templates/header.rs.html
This PR fixes several broken links on https://xeiaso.net/.
Please let me know if this kind of contribution is helpful and if I should do anything differently. I enjoy this kind of tidying up, just want to do it in a way that is most helpful. :)
=> Broken links

blog/2022-media.markdown
Hey, I really enjoyed the article, thanks. Sinadrin jumped at me and then I noticed the other two, hope this is helpful.
(We are holding out on Stray until we can experience it with haptics, did you get your PS5 after playing it?)
=> Fix a few small typos that jumped a bit

dhall/signalboost.dhall
Please let me know if there's anything you'd like me to adjust. Is submitting the PR the only step? 
This is a really nice thing to do for people. I respect it a lot. Thank you.
=> Add zachary sohovich (me) to signal boosts

dhall/signalboost.dhall
=> dhall/signalboost: Drop nicoo

dhall/signalboost.dhall
Appreciate the exposure more than you know :)
=> Cut: Self from signal boost

dhall/signalboost.dhall
=> Add Connor Edwards to signal boost

lume/src/blog/birth-death-seo.mdx
https://pneuma.shark-harmonic.ts.net/blog/birth-death-seo/
=> The birth & death of SEO

dhall/signalboost.dhall
Thanks for having this section on your site! I've seen salary transparency, mutual aid, a handful of pages in similar spirit, but (and perhaps I've just been round the wrong parts) this strikes as rather unique -- were you inspired by a particular mentor or existing practice?
If all goes well I'll just need this up for 1-2 quarters. I may fall back into retail until I've built up a stronger portfolio / certs / back-to-school? idk, i think life has a way of working out if you just keep at it
thx again, and happy new years!
=> signal-boost: add entry for antlers

dhall/signalboost.dhall
Hopefully we did this correctly. It's our first time forking!
=> Adding myself to the signal boost page.

dhall/signalboost.dhall
Thanks Xe, I hope you are well.
=> Remove myself from signalboost

dhall/signalboost.dhall
Thanks for having this page :)
=> add Jerred Shepherd to signal boosts

dhall/signalboost.dhall
=> Remove Evan Pratten from signalboost.dhall

dhall/signalboost.dhall
=> Remove İlteriş Eroğlu from dhall/signalboost.dhall

dhall/signalboost.dhall
=> Add Izzy's signal boost

dhall/signalboost.dhall
ladies and gentlemen, i have job
=> dhall/signalboost: Remove Ryan Heywood
